import Link from 'next/link';import StatCard from '../components/StatCard';import {shows,schedule,songs} from '../data/tour';
export default function Home(){const latest=shows.at(-1);return <div>
<section className="hero"><div className="shell"><p className="eyebrow">North American Tour 2026</p><h1>Every show.<br/>Every song.<br/><em>Every change.</em></h1><p className="lede">A living setlist archive built for fans who want to follow how the tour evolves night after night.</p><div className="actions"><Link className="button primary" href="/shows">Explore shows</Link><Link className="button" href="/stats">View statistics</Link></div></div></section>
<section className="shell section">
<div className="statsGrid"><StatCard label="Shows completed" value={`${shows.length} / ${schedule.length}`} detail="12.5% of the tour"/><StatCard label="Unique songs" value={songs.length}/><StatCard label="Live debuts" value="1" detail="Magic"/><StatCard label="Latest similarity" value="100%" detail="Show #2 vs. Show #1"/></div>
<div className="featureGrid"><article className="panel feature"><p className="eyebrow">Latest show · #{latest.number}</p><h2>{latest.venue}</h2><p className="muted">{latest.city} · {latest.displayDate}</p><p>{latest.notes[0]}</p><Link className="textLink" href={`/shows/${latest.slug}`}>Open full show report →</Link></article>
<article className="panel"><p className="eyebrow">Tour progress</p><div className="progress"><span style={{width:`${shows.length/schedule.length*100}%`}}/></div><h3>{shows.length} of {schedule.length} shows complete</h3><p className="muted">Next scheduled stop: Tinley Park, Illinois.</p></article></div>
</section>
<section className="shell section"><div className="sectionHead"><div><p className="eyebrow">Recent activity</p><h2>Tracked shows</h2></div><Link className="textLink" href="/shows">View all dates →</Link></div><div className="cardGrid">{shows.map(s=><Link className="showCard" key={s.slug} href={`/shows/${s.slug}`}><span>Show #{s.number}</span><h3>{s.venue}</h3><p>{s.city}</p><small>{s.displayDate}</small></Link>)}</div></section>
</div>}